##
# @description Test
# @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
##
name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-typescript:
    name   : TypeScript tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id  : checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id  : setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache       : npm

      - name: Install dependencies
        id  : npm-ci
        run : npm ci

      - name: Check format
        id  : npm-format-check
        run : npm run format:check

      - name: Lint
        id  : npm-lint
        run : npm run lint

  test-action:
    name   : GitHub Actions test
    runs-on: ubuntu-latest

    permissions:
      contents     : write 
      issues       : write 
      pull-requests: write 

    steps:
      - name: Checkout
        id  : checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test local action
        id  : test-action
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
